/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PortfolioIndexImport } from './routes/portfolio/index'
import { Route as PagsIndexImport } from './routes/pags/index'
import { Route as MarketplaceIndexImport } from './routes/marketplace/index'
import { Route as FeedIndexImport } from './routes/feed/index'
import { Route as ProfileSettingsImport } from './routes/profile/settings'
import { Route as ProfileUserIdImport } from './routes/profile/$userId'
import { Route as MarketplaceNftIdImport } from './routes/marketplace/$nftId'
import { Route as ArtistUploadImport } from './routes/artist/upload'
import { Route as ArtistDashboardImport } from './routes/artist/dashboard'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIndexRoute = PortfolioIndexImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any)

const PagsIndexRoute = PagsIndexImport.update({
  id: '/pags/',
  path: '/pags/',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceIndexRoute = MarketplaceIndexImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRoute,
} as any)

const FeedIndexRoute = FeedIndexImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileSettingsRoute = ProfileSettingsImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUserIdRoute = ProfileUserIdImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceNftIdRoute = MarketplaceNftIdImport.update({
  id: '/marketplace/$nftId',
  path: '/marketplace/$nftId',
  getParentRoute: () => rootRoute,
} as any)

const ArtistUploadRoute = ArtistUploadImport.update({
  id: '/artist/upload',
  path: '/artist/upload',
  getParentRoute: () => rootRoute,
} as any)

const ArtistDashboardRoute = ArtistDashboardImport.update({
  id: '/artist/dashboard',
  path: '/artist/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/artist/dashboard': {
      id: '/artist/dashboard'
      path: '/artist/dashboard'
      fullPath: '/artist/dashboard'
      preLoaderRoute: typeof ArtistDashboardImport
      parentRoute: typeof rootRoute
    }
    '/artist/upload': {
      id: '/artist/upload'
      path: '/artist/upload'
      fullPath: '/artist/upload'
      preLoaderRoute: typeof ArtistUploadImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/$nftId': {
      id: '/marketplace/$nftId'
      path: '/marketplace/$nftId'
      fullPath: '/marketplace/$nftId'
      preLoaderRoute: typeof MarketplaceNftIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsImport
      parentRoute: typeof rootRoute
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedIndexImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceIndexImport
      parentRoute: typeof rootRoute
    }
    '/pags/': {
      id: '/pags/'
      path: '/pags'
      fullPath: '/pags'
      preLoaderRoute: typeof PagsIndexImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist/dashboard': typeof ArtistDashboardRoute
  '/artist/upload': typeof ArtistUploadRoute
  '/marketplace/$nftId': typeof MarketplaceNftIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/feed': typeof FeedIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/pags': typeof PagsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist/dashboard': typeof ArtistDashboardRoute
  '/artist/upload': typeof ArtistUploadRoute
  '/marketplace/$nftId': typeof MarketplaceNftIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/feed': typeof FeedIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/pags': typeof PagsIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/artist/dashboard': typeof ArtistDashboardRoute
  '/artist/upload': typeof ArtistUploadRoute
  '/marketplace/$nftId': typeof MarketplaceNftIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/feed/': typeof FeedIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/pags/': typeof PagsIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artist/dashboard'
    | '/artist/upload'
    | '/marketplace/$nftId'
    | '/profile/$userId'
    | '/profile/settings'
    | '/feed'
    | '/marketplace'
    | '/pags'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artist/dashboard'
    | '/artist/upload'
    | '/marketplace/$nftId'
    | '/profile/$userId'
    | '/profile/settings'
    | '/feed'
    | '/marketplace'
    | '/pags'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/artist/dashboard'
    | '/artist/upload'
    | '/marketplace/$nftId'
    | '/profile/$userId'
    | '/profile/settings'
    | '/feed/'
    | '/marketplace/'
    | '/pags/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistDashboardRoute: typeof ArtistDashboardRoute
  ArtistUploadRoute: typeof ArtistUploadRoute
  MarketplaceNftIdRoute: typeof MarketplaceNftIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  FeedIndexRoute: typeof FeedIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  PagsIndexRoute: typeof PagsIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistDashboardRoute: ArtistDashboardRoute,
  ArtistUploadRoute: ArtistUploadRoute,
  MarketplaceNftIdRoute: MarketplaceNftIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  FeedIndexRoute: FeedIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  PagsIndexRoute: PagsIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/artist/dashboard",
        "/artist/upload",
        "/marketplace/$nftId",
        "/profile/$userId",
        "/profile/settings",
        "/feed/",
        "/marketplace/",
        "/pags/",
        "/portfolio/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/artist/dashboard": {
      "filePath": "artist/dashboard.tsx"
    },
    "/artist/upload": {
      "filePath": "artist/upload.tsx"
    },
    "/marketplace/$nftId": {
      "filePath": "marketplace/$nftId.tsx"
    },
    "/profile/$userId": {
      "filePath": "profile/$userId.tsx"
    },
    "/profile/settings": {
      "filePath": "profile/settings.tsx"
    },
    "/feed/": {
      "filePath": "feed/index.tsx"
    },
    "/marketplace/": {
      "filePath": "marketplace/index.tsx"
    },
    "/pags/": {
      "filePath": "pags/index.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
